# -*- coding: utf-8 -*-
"""Braille_Vission_Hackathon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vzaxhea0OxawoU3pQH089QPZ2WyMm3PE
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import matplotlib.pyplot as plt
import json

from google.colab import drive
drive.mount('/content/drive')

IMG_SIZE = 50
BATCH_SIZE = 32
data_dir = "/content/drive/MyDrive/Braaille Vision Hackathon/Braille Alphabet Image Dataset (A–Z)"

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    data_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    color_mode='grayscale',
    class_mode='categorical',
    subset='training'
)

val_generator = train_datagen.flow_from_directory(
    data_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    color_mode='grayscale',
    class_mode='categorical',
    subset='validation'
)

print("Classes:", train_generator.class_indices)

num_classes = len(train_generator.class_indices)

model = keras.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 1)),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(num_classes, activation='softmax')
])

model.summary()

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=20
)

plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Val')
plt.title('Accuracy')
plt.legend()
plt.show()

model.save("/content/drive/MyDrive/Braaille Vision Hackathon/Hackathon/braille_cnn.h5")

class_indices = train_generator.class_indices
reverse_map = {str(v): k for k, v in class_indices.items()}

with open("/content/drive/MyDrive/Braaille Vision Hackathon/Hackathon/reverse_map.json", "w") as f:
    json.dump(reverse_map, f)

print("✅ Model saved!")
print("Classes:", reverse_map)

import shutil
shutil.copy("/content/braille_cnn.onnx", "/content/drive/MyDrive/Braaille Vision Hackathon/Hackathon/braille_cnn.onnx")
print("✅ ONNX saved to Drive!")

import cv2
import os

base = "/content/drive/MyDrive/Braaille Vision Hackathon/Braille Alphabet Image Dataset (A\u2013Z)"
folder = sorted(os.listdir(base))[0]
file = os.listdir(os.path.join(base, folder))[0]
test_path = os.path.join(base, folder, file)

img = cv2.imread(test_path, cv2.IMREAD_GRAYSCALE)
resized = cv2.resize(img, (50, 50))
normalized = resized / 255.0
ready = normalized.reshape(1, 50, 50, 1).astype(np.float32)

prediction = model.predict(ready)
class_index = str(np.argmax(prediction))
letter = reverse_map[class_index]
confidence = np.max(prediction) * 100

print(f"Folder: {folder}")
print(f"Predicted: {letter.upper()}")
print(f"Confidence: {confidence:.1f}%")